import { inject, injectable } from 'inversify';
import { Result } from '@/shared/result/result';
import type { AppConfigRepositoryPort } from '../ports/app-config-repository.port';
import { APP_BUILDER_TYPES } from '../../infrastructure/bootstrap/types';
import type { AppConfig } from '../../domain/entities/app-config.entity';
import type { GrapeJsProjectData } from '../../domain/entities/template.entity';
import { createAppConfig } from '../../domain/entities/app-config.entity';

export interface SaveAppConfigRequest {
  readonly appId: string;
  readonly merchantId: string;
  readonly config: GrapeJsProjectData;
  readonly draftConfig: GrapeJsProjectData;
}

@injectable()
export class SaveAppConfigUseCase {
  constructor(
    @inject(APP_BUILDER_TYPES.AppConfigRepository)
    private readonly repository: AppConfigRepositoryPort
  ) {}

  public async execute(request: SaveAppConfigRequest): Promise<Result<AppConfig, Error>> {
    if (!request.appId || request.appId.trim() === '') {
      return Result.error(new Error('App ID is required'));
    }

    if (!request.merchantId || request.merchantId.trim() === '') {
      return Result.error(new Error('Merchant ID is required'));
    }

    const now = new Date();
    const config = createAppConfig({
      id: '', // Will be generated by database
      appId: request.appId,
      merchantId: request.merchantId,
      config: request.config,
      draftConfig: request.draftConfig,
      version: 1,
      isActive: true,
      createdAt: now,
      updatedAt: now,
    });

    return this.repository.save(config);
  }
}
