import type { OfferScenarioCategoryCode } from '../value-objects/offer-scenario-category.value-object';
import type { OfferTriggerCode } from '../value-objects/offer-trigger.value-object';
import type { OfferActionType } from '../value-objects/offer-action.value-object';
import type { OfferItemProps } from '../value-objects/offer-item.value-object';

export interface OfferScenarioDefinition {
  readonly slug: string;
  readonly title: string;
  readonly description: string;
  readonly categoryCode: OfferScenarioCategoryCode;
  readonly triggerCode: OfferTriggerCode;
  readonly defaultPriority: number;
  readonly defaultActions: OfferActionType[];
  readonly defaultTags?: readonly string[];
  readonly defaultItems?: readonly OfferItemProps[];
}

export const OFFER_SCENARIO_CATALOG: readonly OfferScenarioDefinition[] = [
  {
    slug: 'welcome-new-user',
    title: 'Welcome Offer',
    description: 'First session experience for brand new users with a starter bundle.',
    categoryCode: 'welcome_retention',
    triggerCode: 'new_user_welcome',
    defaultPriority: 90,
    defaultActions: ['discount', 'bonus_currency'],
    defaultTags: ['welcome', 'onboarding'],
  },
  {
    slug: 'returning-trial-offer',
    title: 'Returning Visitor Trial',
    description: 'Bring back returning visitors without purchases via a base trial offer.',
    categoryCode: 'welcome_retention',
    triggerCode: 'returning_no_purchase',
    defaultPriority: 70,
    defaultActions: ['trial_extension', 'reminder'],
  },
  {
    slug: 'reactivation-offer',
    title: 'Win-Back Campaign',
    description: 'Re-engage users inactive for 30+ days with high-value incentives.',
    categoryCode: 'welcome_retention',
    triggerCode: 'inactive_30_days',
    defaultPriority: 100,
    defaultActions: ['discount', 'bonus_currency', 'notification'],
    defaultTags: ['winback'],
  },
  {
    slug: 'motivation-offer',
    title: 'Activity Boost',
    description: 'Motivate low-activity users to re-engage with challenges and boosts.',
    categoryCode: 'welcome_retention',
    triggerCode: 'low_activity',
    defaultPriority: 60,
    defaultActions: ['bonus_currency', 'notification'],
  },
  {
    slug: 'subscription-retention',
    title: 'Subscription Retention',
    description: 'Personalised offer after subscription cancellation to retain customers.',
    categoryCode: 'welcome_retention',
    triggerCode: 'cancelled_subscription',
    defaultPriority: 95,
    defaultActions: ['discount', 'loyalty_upgrade'],
    defaultTags: ['subscription'],
  },
  {
    slug: 'category-follow-up',
    title: 'Category Follow-up',
    description: 'Recommend products aligned with previous purchase categories.',
    categoryCode: 'purchase_spending',
    triggerCode: 'repeat_purchaser',
    defaultPriority: 80,
    defaultActions: ['upsell', 'reminder'],
  },
  {
    slug: 'vip-offer',
    title: 'VIP Recognition',
    description: 'Reward high spenders with exclusive bundles and loyalty upgrades.',
    categoryCode: 'purchase_spending',
    triggerCode: 'high_spender',
    defaultPriority: 100,
    defaultActions: ['discount', 'loyalty_upgrade', 'cosmetic_reward'],
    defaultTags: ['vip'],
  },
  {
    slug: 'first-payment-upsell',
    title: 'First Payment Upsell',
    description: 'Leverage first purchase momentum to upsell higher tier packages.',
    categoryCode: 'purchase_spending',
    triggerCode: 'first_payment',
    defaultPriority: 85,
    defaultActions: ['upsell', 'bonus_currency'],
  },
  {
    slug: 'spend-milestone-bonus',
    title: 'Spend Milestone Bonus',
    description: 'Celebrate lifetime spend milestones with rewards and recognition.',
    categoryCode: 'purchase_spending',
    triggerCode: 'lifetime_spend_milestone',
    defaultPriority: 75,
    defaultActions: ['bonus_currency', 'cosmetic_reward'],
    defaultTags: ['milestone'],
  },
  {
    slug: 'weekly-streak-reward',
    title: 'Weekly Streak Reward',
    description: 'Provide cumulative benefits for multiple purchases in a week.',
    categoryCode: 'purchase_spending',
    triggerCode: 'frequent_weekly_purchases',
    defaultPriority: 65,
    defaultActions: ['bonus_currency', 'loyalty_upgrade'],
  },
  {
    slug: 'product-reminder-offer',
    title: 'Product Reminder',
    description: 'Offer incentive for users repeatedly viewing the same product.',
    categoryCode: 'cart_behavior',
    triggerCode: 'repeat_product_view',
    defaultPriority: 55,
    defaultActions: ['reminder', 'discount'],
  },
  {
    slug: 'cart-recovery-offer',
    title: 'Cart Recovery',
    description: 'Recover abandoned carts with nudges and checkout incentives.',
    categoryCode: 'cart_behavior',
    triggerCode: 'abandoned_cart',
    defaultPriority: 100,
    defaultActions: ['discount', 'notification'],
    defaultTags: ['cart'],
  },
  {
    slug: 'category-intent-offer',
    title: 'Category Intent Offer',
    description: 'Promote curated offers for recently browsed categories.',
    categoryCode: 'cart_behavior',
    triggerCode: 'category_view_intent',
    defaultPriority: 60,
    defaultActions: ['upsell', 'reminder'],
  },
  {
    slug: 'premium-geo-package',
    title: 'Premium Geo Package',
    description: 'Target high income regions with premium bundles.',
    categoryCode: 'geo_pricing',
    triggerCode: 'high_income_region',
    defaultPriority: 70,
    defaultActions: ['upsell', 'cosmetic_reward'],
  },
  {
    slug: 'economy-geo-package',
    title: 'Economy Geo Package',
    description: 'Tailor offers for price-sensitive regions with value bundles.',
    categoryCode: 'geo_pricing',
    triggerCode: 'price_sensitive_region',
    defaultPriority: 80,
    defaultActions: ['discount', 'coupon'],
  },
  {
    slug: 'mbc-exclusive-offer',
    title: 'MBC Exclusive Offer',
    description: 'Provide exclusive bundles for users from the MBC application.',
    categoryCode: 'geo_pricing',
    triggerCode: 'mbc_app_user',
    defaultPriority: 65,
    defaultActions: ['content_unlock', 'bonus_currency'],
  },
  {
    slug: 'annual-upgrade-offer',
    title: 'Annual Upgrade',
    description: 'Upsell monthly subscribers to annual plans with incentives.',
    categoryCode: 'promo_seasonal',
    triggerCode: 'monthly_to_yearly_upsell',
    defaultPriority: 90,
    defaultActions: ['discount', 'trial_extension'],
  },
  {
    slug: 'influencer-bonus-offer',
    title: 'Influencer Bonus',
    description: 'Reward influencer-driven purchases with referral bonuses.',
    categoryCode: 'promo_seasonal',
    triggerCode: 'influencer_promo_purchase',
    defaultPriority: 70,
    defaultActions: ['bonus_currency', 'coupon'],
  },
  {
    slug: 'weekend-special-offer',
    title: 'Weekend Special',
    description: 'Run weekend special promotions with exclusives.',
    categoryCode: 'promo_seasonal',
    triggerCode: 'weekend_purchase',
    defaultPriority: 60,
    defaultActions: ['discount', 'cosmetic_reward'],
    defaultTags: ['weekend'],
  },
  {
    slug: 'high-activity-cosmetics',
    title: 'High Activity Cosmetics',
    description: 'Grant exclusive cosmetics for highly active players.',
    categoryCode: 'promo_seasonal',
    triggerCode: 'high_activity_reward',
    defaultPriority: 50,
    defaultActions: ['cosmetic_reward'],
  },
] as const;
