export const env = {
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_USE_SUPABASE_REVENUE: process.env.NEXT_PUBLIC_USE_SUPABASE_REVENUE,
  NEXT_PUBLIC_USE_SUPABASE_PURCHASE: process.env.NEXT_PUBLIC_USE_SUPABASE_PURCHASE,
  NEXT_PUBLIC_USE_SUPABASE_OFFERS: process.env.NEXT_PUBLIC_USE_SUPABASE_OFFERS,
  NEXT_PUBLIC_CLIENT_URL: process.env.NEXT_PUBLIC_CLIENT_URL,
};
